name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 4b39e78b-0ea3-4732-a85e-de3b67b1f42f
          heroku_app_name: rahalbimsarathennakoon
          heroku_email: rahalbimsarathennakoon@outlook.com
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_CONFIG_FILE_URL: https://gist.githubusercontent.com/rahalbimsarathennakoon/121071d698c676c51fe2ecf119ca7ca4/raw/config.env
